apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: eligibility-app
type: Opaque
data:
  # These are placeholder values - replace with actual base64 encoded secrets in production
  # To encode: echo -n "your-password" | base64
  password: <BASE64_ENCODED_PASSWORD>  # Replace this
  username: <BASE64_ENCODED_USERNAME>  # Replace this

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: eligibility-app
type: Opaque
data:
  jwt-secret: <BASE64_ENCODED_JWT_SECRET>  # Replace this
  api-key: <BASE64_ENCODED_API_KEY>        # Replace this

---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: eligibility-app
type: Opaque
data:
  admin-password: <BASE64_ENCODED_GRAFANA_PASSWORD>  # Replace this

---
apiVersion: v1
kind: Secret
metadata:
  name: glitchtip-secret
  namespace: eligibility-app
type: Opaque
data:
  secret-key: <BASE64_ENCODED_GLITCHTIP_SECRET>  # Replace this